[package]
name = "rpc-cloudfunc-middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
log = "0.4.19"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
